# Form implementation generated from reading ui file '.\ui\add_reservation.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(781, 300)
        Dialog.setMinimumSize(QtCore.QSize(300, 300))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.title = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.verticalLayout.addWidget(self.title, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.client_label = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.client_label.setFont(font)
        self.client_label.setObjectName("client_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.client_label)
        self.client_combobox = QtWidgets.QComboBox(parent=Dialog)
        self.client_combobox.setObjectName("client_combobox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.client_combobox)
        self.room_number = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.room_number.setFont(font)
        self.room_number.setObjectName("room_number")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.room_number)
        self.room_combobox = QtWidgets.QComboBox(parent=Dialog)
        self.room_combobox.setObjectName("room_combobox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.room_combobox)
        self.check_in_date = QtWidgets.QLabel(parent=Dialog)
        self.check_in_date.setObjectName("check_in_date")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.check_in_date)
        self.check_in_date1 = QtWidgets.QDateEdit(parent=Dialog)
        self.check_in_date1.setObjectName("check_in_date1")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.check_in_date1)
        self.check_out = QtWidgets.QLabel(parent=Dialog)
        self.check_out.setObjectName("check_out")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.check_out)
        self.check_out_date = QtWidgets.QDateEdit(parent=Dialog)
        self.check_out_date.setObjectName("check_out_date")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.check_out_date)
        self.verticalLayout.addLayout(self.formLayout)
        self.add_button = QtWidgets.QPushButton(parent=Dialog)
        self.add_button.setObjectName("add_button")
        self.verticalLayout.addWidget(self.add_button)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.title.setText(_translate("Dialog", "Добавить бронирование"))
        self.client_label.setText(_translate("Dialog", "Клиент"))
        self.room_number.setText(_translate("Dialog", "Номер"))
        self.check_in_date.setText(_translate("Dialog", "Дата въезда"))
        self.check_out.setText(_translate("Dialog", "Дата выезда"))
        self.add_button.setText(_translate("Dialog", "Добавить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
